platform:ios, '7.0'

target "VKVickey_NCE" do

pod 'Masonry', '~> 1.0'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 3.0'
pod 'MJRefresh', '~> 3.0'
pod 'FMDB', '~> 2.0'
pod 'MBProgressHUD', '~> 1.0'

#pod 'UMengSocialCOM', '~> 5.0'
pod 'UMengAnalytics-NO-IDFA', '~> 4.0'
pod 'UMengMessage-NO-IDFA-SUN', '~> 1.3'

end
